### ISSUE TITLE
who can show me a correct config for reference or show me where i am wrong

### ISSUE THREAD

**Issue by ziyingjie** [Dineshkarthik/telegram_media_downloader#106]
**this is my config**
api_hash:***
api_id: ***
chat_id: ***
file_formats: all
ids_to_retry: []
last_read_message_id: 3555
media_types: photo

**this is the logs The program will exit automatically**

INFO:media_downloader:Device: CPython 3.8.5 - Telegram Media Downloader 1.0.0
INFO:media_downloader:System: Windows 10 (EN)
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:1000
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:1000
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:1000
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
INFO:pyrogram.connection.transport.tcp.tcp:Using proxy 127.0.0.1:1000
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.internals.msg_id:Time synced: 2021-08-21 07:44:07.460558 UTC
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 36m 20s (at 2021-08-21 16:20:28)
INFO:pyrogram.session.session:Session initialized: Layer 126
INFO:pyrogram.session.session:Device: CPython 3.8.5 - Pyrogram 1.2.6
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.dispatcher:Started 8 HandlerTasks
INFO:pyrogram.syncer:Synced "media_downloader" in 219.525 ms
INFO:pyrogram.syncer:Synced "media_downloader" in 286.127 ms
INFO:pyrogram.dispatcher:Stopped 8 HandlerTasks
INFO:pyrogram.session.session:PingTask stopped
INFO:pyrogram.session.session:NextSaltTask stopped
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
INFO:media_downloader:Updated last read message_id to config file
PS E:\telegram_media_downloader-1.0.0>
**who can show me a correct config for reference or show me where i am wrong**
**I'm really very thankful to you for your help.**

**Comment by ziyingjie** [comment]
i am  Exhausted

**Comment by Dineshkarthik** [comment]
```api_hash:***
api_id: ***
chat_id: ***
ids_to_retry: []
last_read_message_id: 0
media_types:
- photo
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
```
This should work @ziyingjie
