### ISSUE TITLE
how to get chat id

### ISSUE THREAD

**Issue by scryptio** [Dineshkarthik/telegram_media_downloader#113]
How to get the chatid in 2021? The url now leads to "https://web.telegram.org/k/" so there is nothing in the URL.

**Comment by Dineshkarthik** [comment]
You can actually switch back to the legacy by using this url - https://web.telegram.org/?legacy=1#/im
or you can use any of the user info bot to get the ids, ex: `@username_to_id_bot` just forward a message from a user to the id of the user or copy paste the invite link of the public or private channel and you will get the chat id.
