### ISSUE TITLE
save description/comment with media

### ISSUE THREAD

**Issue by RedAuburn** [Dineshkarthik/telegram_media_downloader#174]
**Is your feature request related to a problem? Please describe.**
i'm scraping media, and the comments are quite important for the context of the video.

**Describe the solution you'd like**
an option to save the comment that the media was posted with either in the metadata of the media, or as a separate file.

**Comment by rmdes** [comment]
Saving the context in either JSON with the same filename of the download would be interesting perhaps, so to retain original context of the download origin ?

**Comment by tangyoha** [comment]
see [telegram_media_downloader]（https://github.com/tangyoha/telegram_media_downloader）
`config.yaml` add `file_name_prefix` to save caption
