### ISSUE TITLE
Cant load module

### ISSUE THREAD

**Issue by awolffrommars** [Dineshkarthik/telegram_media_downloader#214]
It shows me these errors, any way to fix it?

ModuleNotFoundError: No module named 'pyrogram'
ModuleNotFoundError: No module named 'yaml'

**Comment by Dineshkarthik** [comment]
you need to install the required packages. Follow the [install instructions](https://github.com/Dineshkarthik/telegram_media_downloader#installation).

**Comment by awolffrommars** [comment]
> you need to install the required packages. Follow the [install instructions](https://github.com/Dineshkarthik/telegram_media_downloader#installation).

Already did, but it still shows me same errors. If it helps im using the command `py ` instead of `python3` when executing because python3 doesnt work for me

**Comment by awolffrommars** [comment]
Installed the packages separately and it seems to be working now
