### ISSUE TITLE
Handlertaks error or something not sure

### ISSUE THREAD

**Issue by sunny9t1** [Dineshkarthik/telegram_media_downloader#239]
Device: CPython 3.9.11 - Pyrogram 1.4.12                                              session.py:132
           INFO     System: Windows 10 (EN)                                                               session.py:133
           INFO     Session started                                                                       session.py:148
           INFO     PingTask started                                                                      session.py:250
[01:32:25] INFO     Started 8 HandlerTasks                                                             dispatcher.py:136
[01:32:26] INFO     Stopped 8 HandlerTasks                                                             dispatcher.py:149
           INFO     PingTask stopped                                                                      session.py:269
           INFO     Disconnected                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                   session.py:288
           INFO     Session stopped                                                                       session.py:174
           INFO     Updated last read message_id to config file                                   media_downloader.py:47
PS E:\Telegram\telegram_media_downloader\telegram_media_downloader>

now i have been getting the above error all the time.. it worked very well for almost all day now its just showing this

**Comment by Dineshkarthik** [comment]
Hi,
This is not an error as you can see this has the label `INFO` which relates to some information for user visibility. I assume that there are no more media of configured type in config.yaml available in the channel you are trying to download.
