### ISSUE TITLE
Would like Add socks5 proxy support

### ISSUE THREAD

**Issue by didiva** [Dineshkarthik/telegram_media_downloader#240]
For now the telegram_media_downloader program only support direct connect to telegram server.
Is there anyway to add socks5 proxy server support?
Include the local proxy server or remote proxy server, and can make config in config files.
Thanks.

**Comment by Dineshkarthik** [comment]
Read the `README.md` file fully. Proxy is already available and instructions can be found under section [Proxy](https://github.com/Dineshkarthik/telegram_media_downloader#proxy)
