### ISSUE TITLE
 NetworkTask stopped 

### ISSUE THREAD

**Issue by Falcon87262** [Dineshkarthik/telegram_media_downloader#253]
Hi
i dont know what is wrong here  
i am connected to betternet vpn 
vpn works fine if i use google site but 
i am getting this constantly
`(venv) root@Falcon:/mnt/d/telegram/telegram_media_downloader# python media_downloader.py
[19:34:25] Telegram Media Downloader v1.5.1,                                                                                                                  meta.py:20
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                                                                        meta.py:23

[19:34:25] INFO     Device: CPython 3.8.10 - Telegram Media Downloader 1.5.1                                                                                  meta.py:24
           INFO     System: Linux 5.4.72-microsoft-standard-WSL2 (EN)                                                                                         meta.py:25
[19:34:56] INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:34:57] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:34:58] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:34:59] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
           INFO     Time synced: 2022-06-16 14:34:59.480199 UTC                                                                                             msg_id.py:45
[19:35:00] INFO     Session initialized: Layer 139                                                                                                        session.py:131
           INFO     Device: CPython 3.8.10 - Pyrogram 1.4.12                                                                                              session.py:132
           INFO     System: Linux 5.4.72-microsoft-standard-WSL2 (EN)                                                                                     session.py:133
           INFO     Session started                                                                                                                       session.py:148
           INFO     PingTask started                                                                                                                      session.py:250
[19:35:01] INFO     Started 8 HandlerTasks                                                                                                             dispatcher.py:136
[19:35:04] INFO     Start creating a new auth key on DC2                                                                                                      auth.py:82
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC2 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
[19:35:10] INFO     Done auth key exchange: DhGenOk                                                                                                          auth.py:249
           INFO     Disconnected                                                                                                                        connection.py:77
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC2 (media) - IPv4 - TCPAbridgedO                                                                             connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:11] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC2 (media) - IPv4 - TCPAbridgedO                                                                             connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:13] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC2 (media) - IPv4 - TCPAbridgedO                                                                             connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:14] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC2 (media) - IPv4 - TCPAbridgedO                                                                             connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:16] INFO     Session initialized: Layer 139                                                                                                        session.py:131
           INFO     Device: CPython 3.8.10 - Pyrogram 1.4.12                                                                                              session.py:132
           INFO     System: Linux 5.4.72-microsoft-standard-WSL2 (EN)                                                                                     session.py:133
           INFO     Session started                                                                                                                       session.py:148
           INFO     PingTask started                                                                                                                      session.py:250
[19:35:26] INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     PingTask stopped                                                                                                                      session.py:269
           INFO     Disconnected                                                                                                                        connection.py:77
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:27] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:28] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:29] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:30] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:31] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:32] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:33] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:34] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:35] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:36] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
[19:35:37] INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:38] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:39] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:40] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:41] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:42] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:43] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:44] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:45] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:46] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:47] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:48] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:49] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:50] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:51] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:52] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:53] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:54] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
[19:35:55] INFO     Disconnected                                                                                                                        connection.py:77
           INFO     NetworkTask stopped                                                                                                                   session.py:288
           INFO     Session stopped                                                                                                                       session.py:174
           INFO     Connecting...                                                                                                                       connection.py:56
           INFO     Connected! Production DC1 - IPv4 - TCPAbridgedO                                                                                     connection.py:63
           INFO     NetworkTask started                                                                                                                   session.py:272
           INFO     NetworkTask stopped
Traceback (most recent call last):
  File "media_downloader.py", line 380, in <module>
    main()
  File "media_downloader.py", line 364, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by q847633684** [comment]
估计你的vpn不稳定，试试换别的vpn.或者使用SOCKS5代理。
