### ISSUE TITLE
An error is reported after running

### ISSUE THREAD

**Issue by icefins** [Dineshkarthik/telegram_media_downloader#271]
# python3 media_downloader.py
[10:12:17] Telegram Media Downloader v1.5.1,
meta.py:20           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
Licensed under the terms of the MIT License
meta.py:23
[10:12:17] INFO     Device: CPython 3.9.6 - Telegram Media Downloader 1.5.1
meta.py:24           INFO     System: Linux 3.4.39 (EN)
meta.py:25[10:12:19] INFO     Connecting... 
connection.py:56           INFO     Connected! Production DC5 - IPv4 - TCPAbridgedO
connection.py:63           INFO     NetworkTask started
session.py:272           INFO     Time synced: 2022-07-16 10:12:19.264468 UTC
msg_id.py:45           INFO     Session initialized: Layer 139
session.py:131           INFO     Device: CPython 3.9.6 - Pyrogram 1.4.12
session.py:132           INFO     System: Linux 3.4.39 (EN)
session.py:133           INFO     Session started
session.py:148           INFO     PingTask started
session.py:250           INFO     Started 8 HandlerTasks
dispatcher.py:136[10:12:20] INFO     Stopped 8 HandlerTasks
dispatcher.py:149           INFO     PingTask stopped
session.py:269           INFO     Disconnected
connection.py:77           INFO     NetworkTask stopped
session.py:288           INFO     Session stopped
session.py:174           INFO     Updated last read message_id to config file
media_downloader.py:47[10:12:20] Following error occured when checking for updates
updates.py:38           <class 'AttributeError'>, module 'http.client' has no attribute 'HTTPSConnection'

**Comment by icefins** [comment]
I found out that this is caused by openssl not being referenced. I fixed it.
But now I have a new problem, still about updating the module.
`python3 media_downloader.py 
[11:57:09] Telegram Media Downloader v1.5.1,                            meta.py:20           Copyright (C) 2019 Dineshkarthik                                       
           <https://github.com/Dineshkarthik>                                     
           Licensed under the terms of the MIT License                  meta.py:23                                                                                  
[11:57:09] INFO     Device: CPython 3.9.6 - Telegram Media Downloader   meta.py:24                    1.5.1                                                         
           INFO     System: Linux 3.4.39 (EN)                           meta.py:25[11:57:11] INFO     Connecting...                                 connection.py:56           INFO     Connected! Production DC5 - IPv4 -            connection.py:63                    TCPAbridgedO                                                  
           INFO     NetworkTask started                             session.py:272           INFO     Time synced: 2022-07-17 11:57:11.358095 UTC       msg_id.py:45[11:57:12] INFO     Session initialized: Layer 139                  session.py:131           INFO     Device: CPython 3.9.6 - Pyrogram 1.4.12         session.py:132           INFO     System: Linux 3.4.39 (EN)                       session.py:133           INFO     Session started                                 session.py:148           INFO     PingTask started                                session.py:250[11:57:13] INFO     Started 8 HandlerTasks                       dispatcher.py:136[11:57:14] INFO     Stopped 8 HandlerTasks                       dispatcher.py:149           INFO     PingTask stopped                                session.py:269           INFO     Disconnected                                  connection.py:77           INFO     NetworkTask stopped                             session.py:288           INFO     Session stopped                                 session.py:174           INFO     Updated last read message_id to config  media_downloader.py:48                    file                                                          
[11:57:25] Following error occured when checking for updates         updates.py:38           <class 'ssl.SSLCertVerificationError'>, [SSL:                          
           CERTIFICATE_VERIFY_FAILED] certificate verify failed:                  
           unable to get local issuer certificate (_ssl.c:1129)                   `

**Comment by Dineshkarthik** [comment]
@icefins this is from the `updates` module, this script will check for any new release of telegram media downloader and this error doesn't affect the media downloader script's functionalities.

**Comment by icefins** [comment]
I confirm that I have introduced the ssl module correctly, how do I block the module update to make it work properly.

**Comment by icefins** [comment]
@Dineshkarthik 
But it stops here at the update error and doesn't continue downloading anymore.

**Comment by Dineshkarthik** [comment]
@icefins the checking for updates is the last step, also what you see is an error message, the error is handled and just the error message is logged. 

There is no new messages or new media files based on your config to download that is why this no new downloads.

**Comment by icefins** [comment]
@Dineshkarthik 
Thanks to you, I solved the problem。

sudo apt install ca-certificates
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs
