### ISSUE TITLE
DOC: No documented how to get id when format is p=gNNNNNNNNN

### ISSUE THREAD

**Issue by manolo** [Dineshkarthik/telegram_media_downloader#278]
#### Location of the documentation

[README](README.md)

#### Documentation problem

I have this channel, but cannot find this pattern in the documentation 

`https://web.telegram.org/?legacy=1#/im?p=g123456789` (note 'g' prefix plus 9 numbers)

#### Suggested fix for documentation

No suggetion, since I cannot figure out the working id

**Comment by Dineshkarthik** [comment]
@manolo thanks for reporting, i am planning to add some helper script which will list the channels, chats the user is a part of and their respective ids.

**Comment by Rhilip** [comment]
juet very simple replace `g` prefix to `-`. 
Like [g123456789](https://web.telegram.org/?legacy=1#/im?p=g123456789) to `-123456789`
