### ISSUE TITLE
DL from multiple chat/group_id's

### ISSUE THREAD

**Issue by icepaule** [Dineshkarthik/telegram_media_downloader#292]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Having the chance to download more that just one chat-, group-id.
Right now having to create multiple instances of config.yaml to achieve this.

Thanks for that great work. - Really appreciated.

**Comment by Dineshkarthik** [comment]
@icepaule closed this issue as there is already an existing one, planning on working on this and this will be mostly int he next release.
