### ISSUE TITLE
NetworkTask stopped

### ISSUE THREAD

**Issue by icefins** [Dineshkarthik/telegram_media_downloader#294]
**Describe the bug**
A clear and con          
INFO     Device: CPython 3.9.6 -Pyrogram 2.0.33 session.py:132
INFO     System: Linux 3.4.39 (EN)                       session.py:133           
INFO     Session started                                 session.py:148           INFO     PingTask started                                session.py:249           INFO     Start creating a new auth key on DC1  auth.py:82           INFO     Connecting...                                 connection.py:56
INFO     Connected! Production DC1 - IPv4 - connection.py:63
TCPAbridgedO                                                  
[01:13:42] INFO     Done auth key exchange: DhGenOkauth.py:249           
INFO     Disconnected                                  connection.py:77
INFO     Connecting...                                 connection.py:56
INFO     Connected! Production DC1 (media) - IPv4-connection.py:63                    
TCPAbridgedO                                                  
INFO     NetworkTask started
session.py:271[01:13:51] 
INFO     NetworkTask stopped                             session.py:287
[01:13:53] INFO     NetworkTask stopped             session.py:287

**Comment by Dineshkarthik** [comment]
These are logs. The table `INFO` means this is not an error that stops this script from working.
