### ISSUE TITLE
网络错误  代理不运行

### ISSUE THREAD

**Issue by yubonijin** [Dineshkarthik/telegram_media_downloader#295]
<img width="1028" alt="截屏2022-07-24 下午9 19 04" src="https://user-images.githubusercontent.com/105959777/180648959-8161c233-c19a-40ff-b555-fd9211a117a5.png">
<img width="325" alt="截屏2022-07-24 下午9 19 48" src="https://user-images.githubusercontent.com/105959777/180648962-ec0dd7f3-1d16-4bb9-9970-fc19ce4b8d56.png">

**Comment by Dineshkarthik** [comment]
remove `username` & `password` from the proxy section in the config.yaml

**Comment by yubonijin** [comment]
谢谢您的回答   我按您说的更改了配置  但是还是一样的错误
![1658706161309](https://user-images.githubusercontent.com/105959777/180670704-53672b44-3350-442e-86b1-da4ebe07c458.png)

**Comment by yubonijin** [comment]
谢谢您的回答   但我更改了配置    结果是一样的   
![1658706318591](https://user-images.githubusercontent.com/105959777/180670804-2e4c1b5b-e7a5-47e8-9708-cdc81c7d6e55.png)

**Comment by XHXJ** [comment]
我也遇到一样的问题,代理没有生效
