### ISSUE TITLE
Not sure what I'm doing wrong

### ISSUE THREAD

**Issue by MarcosBL** [Dineshkarthik/telegram_media_downloader#3]
It seems I can't make it work with Python 3.5.2 ...

![image](https://user-images.githubusercontent.com/389801/63364892-bf9ff800-c376-11e9-8901-7bbd9d7640e8.png)

**Comment by Dineshkarthik** [comment]
@MarcosBL sorry my bad, I updated the python version support as 3.4 and above but used python type hints in my code, which is supported from python 3.6.

Can you run the same with `python version 3.6 or above`
