### ISSUE TITLE
Enter phone number or bot token

### ISSUE THREAD

**Issue by Tonemoretime** [Dineshkarthik/telegram_media_downloader#307]
Display after entering anything: enter phone number or bot token
Telegram Media Downloader v2.0.2
windowns 11
python 3.10

**Comment by ildyria** [comment]
Same.
Python 3.10
Debian SID.

**Comment by caozhg** [comment]
Same. 
telegram_media_downloader-2.0.2
python 3.8.3
windows 10
----------------
v1.5.1 is ok.

**Comment by holore** [comment]
以国际手机号形式输入你的手机
