### ISSUE TITLE
Task ID

### ISSUE THREAD

**Issue by loeveo** [Dineshkarthik/telegram_media_downloader#31]
1.Hope to display the current download task, or the completed task ID. It is convenient to pass the completed task. To calculate the remaining time
2.Hope to download by file id
3.I hope that the completed task id can be modified in real time. Otherwise, after the task is interrupted, the download needs to be restarted

**Comment by Dineshkarthik** [comment]
> 1. Hope to display the current download task, or the completed task ID. It is convenient to pass the completed task. To calculate the remaining time

It is not easy to calculate the remaining time based on the number of messages,  it is based on the size of the files to be downloaded. But will take this to the backlog list and will add later when similar features are implemented.

> 2. Hope to download by file id

That is going too deep and will be used by a very small group of users and it doesn't add much value to the overall community as of now. So won't be adding the feature. But you are welcome to create PR with this feature as an optional argument in the config.yaml

> 3. I hope that the completed task id can be modified in real time. Otherwise, after the task is interrupted, the download needs to be restarted> 3.I hope that the completed task id can be modified in real time. Otherwise, after the task is interrupted, the download needs to be restarted

#50 this fixed the above-mentioned issue, even though it is now updated realtime this is done in batches so it will solve the problem except for some edge cases.
