### ISSUE TITLE
circle shaped videos doesn't download

### ISSUE THREAD

**Issue by nicoday** [Dineshkarthik/telegram_media_downloader#324]
Rounded videos doesn't seems to download. I'm talking about circle shaped videos that under voice message tab in Telegram.

ERROR Message[13041]: could not be
downloaded due to following
exception:
[[Errno 22] Invalid argument:
'C:\\Users\\Alex\\AppData\\Local\\P
rograms\\Python\\Python38\\telegram
_media_downloader-master\\video_not
e\\video_note_2022-09-12T01:01:01.m
p4'].
Traceback (most recent call last):
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\shutil.py",
line 791, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The
filename, directory name, or volume
label syntax is incorrect:
'C:\\Users\\Alex\\AppData\\Local\\T
emp\\tmptlz8qmxl' ->
'C:\\Users\\Alex\\AppData\\Local\\P
rograms\\Python\\Python38\\telegram
_media_downloader-master\\video_not
e\\video_note_2022-09-12T01:01:01.m
p4'

During handling of the above
exception, another exception
occurred:

Traceback (most recent call last):
  File "media_downloader.py", line
191, in download_media
    download_path = await
client.download_media(
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\site-package
s\pyrogram\methods\messages\downloa
d_media.py", line 183, in
download_media
    return await downloader
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\site-package
s\pyrogram\client.py", line 748, in
handle_download
    shutil.move(file.name,
file_path)
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\shutil.py",
line 805, in move
    copy_function(src, real_dst)
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\shutil.py",
line 435, in copy2
    copyfile(src, dst,
follow_symlinks=follow_symlinks)
  File
"C:\Users\Alex\AppData\Local\Progra
ms\Python\Python38\lib\shutil.py",
line 264, in copyfile
    with open(src, 'rb') as fsrc,
open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid
argument:
'C:\\Users\\Alex\\AppData\\Local\\P
rograms\\Python\\Python38\\telegram
_media_downloader-master\\video_not
e\\video_note_2022-09-12T01:01:01.m
p4'

**Comment by XiaoMiHongZhaJi** [comment]
find `media_obj.date.isoformat()` 
and change to 
`media_obj.date.isoformat().replace(":", "-")`
