### ISSUE TITLE
Interger too big

### ISSUE THREAD

**Issue by BobbyC9822** [Dineshkarthik/telegram_media_downloader#327]
After install and configuring the config.yaml file on initially running media_downloader.py I get the following error... 

"int.py", line 33, in __new__
    return value.to_bytes(cls.SIZE, "little", signed=signed)
OverflowError: int too big to convert

Can someone help me figure out what I'm doing wrong or what I need to change to fix this error?

**Comment by Dineshkarthik** [comment]
Please follow the issue template and update the issue
