### ISSUE TITLE
why this is happening

### ISSUE THREAD

**Issue by ThatDevCoder** [Dineshkarthik/telegram_media_downloader#34]
```INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 34m 15s (2020-07-29 16:16:57)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:root:Started 4 UpdatesWorkerTasks
INFO:root:Started 4 DownloadWorkerTasks
INFO:root:Started 4 UpdateWorkerTasks
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 278.53 ms
INFO:pyrogram.session.auth:Start creating a new auth key on DC1
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC1 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.auth:Done auth key exchange: DhGenOk
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC1 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 44m 59s (2020-07-29 16:27:46)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.session.auth:Start creating a new auth key on DC4
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.auth:Done auth key exchange: DhGenOk
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 44m 60s (2020-07-29 16:27:51)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 34m 4s (2020-07-29 16:16:57)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 644.726 ms
INFO:pyrogram.session.session:[1] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[1] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[2] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[2] Retrying functions.upload.GetFile due to
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 719.007 ms
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:[3] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[3] Retrying functions.upload.GetFile due to
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 687.741 ms
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:[4] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[4] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 447.646 ms
WARNING:pyrogram.session.session:[5] Retrying functions.upload.GetFile due to
WARNING:pyrogram.session.session:[5] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:Send 8 acks
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyrogram\client\client.py", line 2015, in get_file
    r = await session.send(
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 415, in send
    raise e from None
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 412, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 391, in _send
    raise TimeoutError
TimeoutError
INFO:__main__:Media downloaded - None
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyrogram\client\client.py", line 2015, in get_file
    r = await session.send(
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 415, in send
    raise e from None
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 412, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 391, in _send
    raise TimeoutError
TimeoutError
```

**Comment by ThatDevCoder** [comment]
` INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 34m 15s (2020-07-29 16:16:57)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:root:Started 4 UpdatesWorkerTasks
INFO:root:Started 4 DownloadWorkerTasks
INFO:root:Started 4 UpdateWorkerTasks
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 278.53 ms
INFO:pyrogram.session.auth:Start creating a new auth key on DC1
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC1 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.auth:Done auth key exchange: DhGenOk
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC1 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 44m 59s (2020-07-29 16:27:46)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.session.auth:Start creating a new auth key on DC4
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.auth:Done auth key exchange: DhGenOk
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC4 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 44m 60s (2020-07-29 16:27:51)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:root:NetWorkerTask started
INFO:pyrogram.session.session:RecvTask started
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 34m 4s (2020-07-29 16:16:57)
INFO:pyrogram.session.session:Session initialized: Layer 112
INFO:pyrogram.session.session:Device: CPython 3.8.3 - Pyrogram 0.17.1-async
INFO:pyrogram.session.session:System: Windows 10 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 644.726 ms
INFO:pyrogram.session.session:[1] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[1] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[2] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[2] Retrying functions.upload.GetFile due to
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 719.007 ms
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:[3] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[3] Retrying functions.upload.GetFile due to
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 687.741 ms
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:[4] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:[4] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.client.ext.syncer:Synced "media_downloader" in 447.646 ms
WARNING:pyrogram.session.session:[5] Retrying functions.upload.GetFile due to
WARNING:pyrogram.session.session:[5] Retrying functions.upload.GetFile due to
INFO:pyrogram.session.session:Send 8 acks
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyrogram\client\client.py", line 2015, in get_file
    r = await session.send(
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 415, in send
    raise e from None
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 412, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 391, in _send
    raise TimeoutError
TimeoutError
INFO:__main__:Media downloaded - None
ERROR:pyrogram.client.client:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\pyrogram\client\client.py", line 2015, in get_file
    r = await session.send(
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 423, in send
    return await self.send(data, retries - 1, timeout)
  [Previous line repeated 2 more times]
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 415, in send
    raise e from None
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 412, in send
    return await self._send(data, timeout=timeout)
  File "C:\Python38\lib\site-packages\pyrogram\session\session.py", line 391, in _send
    raise TimeoutError
TimeoutError `

**Comment by Dineshkarthik** [comment]
@ThatDevCoder it seems your network is unable to connect to telegram can you re-try or try with a different network
