### ISSUE TITLE
WIN 7系統，已經安裝了python，還是運行報錯。

### ISSUE THREAD

**Issue by tsinit2001** [Dineshkarthik/telegram_media_downloader#355]
最初用一個1.51版本的是可以運行的，此後歷次升級的新版本，都會提示錯誤。

PS E:\tg\td5>  python media_downloader.py
[20:01:40] Telegram Media Downloader v2.0.2,                                                                 meta.py:18
           Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
           Licensed under the terms of the MIT License                                                       meta.py:21

[20:01:40] INFO     Device: CPython 3.8.2 - Telegram Media Downloader 2.0.2                                  meta.py:22
           INFO     System: Windows 7 (EN)                                                                   meta.py:23
Traceback (most recent call last):
  File "media_downloader.py", line 376, in <module>
    main()
  File "media_downloader.py", line 358, in main
    with open(os.path.join(THIS_DIR, "config.yaml")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\tg\\td5\\config.yaml'
PS E:\tg\td5>

**Comment by tsinit2001** [comment]
代理設置是好的，可以正常使用。且我剛剛又切換回到1.5.1版本，試用也是正常的。

**Comment by tangyoha** [comment]
@tsinit2001 ,please check if the file exist which named `E:\tg\td5\config.yaml`.

**Comment by tsinit2001** [comment]
> 
它在這裏。
![圖片](https://user-images.githubusercontent.com/67938914/200362394-3c31cd35-9aec-44dd-a2cf-9ffb6f5d0444.png)
![圖片](https://user-images.githubusercontent.com/67938914/200362553-1d396ab4-a903-4d98-accc-3c1c9363b5c7.png)

我遇到的問題，應該不是缺乏了配置文件。
目前已經更新了2.0.2版本，可以正常使用了。謝謝。
