### ISSUE TITLE
When the download file is close to 100, it will be interrupted. "last_read_message_id: 0" in config.yaml does not update download progress.

### ISSUE THREAD

**Issue by tsinit2001** [Dineshkarthik/telegram_media_downloader#372]
Traceback (most recent call last):
  File ".\media_downloader.py", line 376, in <module>
    main()
  File ".\media_downloader.py", line 360, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 616, in run_u
ntil_complete
    return future.result()
  File ".\media_downloader.py", line 342, in begin_import
    update_config(config)
  File ".\media_downloader.py", line 42, in update_config
    list(set(config["ids_to_retry"]) - set(DOWNLOADED_IDS)) + FAILED_IDS
TypeError: 'NoneType' object is not iterable

**Comment by tangyoha** [comment]
@ tsinit2001 hi, what is `interrupted`? check you config if exist `ids_to_retry`.
like this
```yaml
ids_to_retry : []
```

**Comment by tsinit2001** [comment]
> @ tsinit2001 hi, what is `interrupted`? check you config if exist `ids_to_retry`. like this
> 
> ```yaml
> ids_to_retry : []
> ```

It is empty.

`api_hash: *
api_id: *
chat_id: *
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry:
last_read_message_id: 0
media_types:
- audio
- photo
- video
- document
- voice
- video_note`

**Comment by tsinit2001** [comment]
> @ tsinit2001 hi, what is `interrupted`? check you config if exist `ids_to_retry`. like this
> 
> ```yaml
> ids_to_retry : []
> ```

yes you are right！
In my config.yaml, I added "[ ]" to "ids_to_retry: ". It works fine now.
I don't know when, I lost the "[ ]" pair of symbols, no wonder the operation will report an error and terminate.
Problem finally solved.
Thanks!
