### ISSUE TITLE
about some downloaded file size is 0bit

### ISSUE THREAD

**Issue by Richman881** [Dineshkarthik/telegram_media_downloader#377]
Because of the network error, it is 0bit after some files are downloaded, which is actually not. Therefore, if the downloaded file size is 0bit, it is defined as a re -download？

**Comment by tangyoha** [comment]
@Richman881 hi，what is meaning network error？can you show me the error log or more info about that.

**Comment by Richman881** [comment]
My network is not very stable because I use a VPN, so when I download, some random files appear with 0bit, but the file is not 0bit in telegram.i'll push some pics bout that later

**Comment by tangyoha** [comment]
> My network is not very stable because I use a VPN, so when I download, some random files appear with 0bit, but the file is not 0bit in telegram.i'll push some pics bout that later

@Richman881 hi，i know it，that is a bug. You can use the beta ver if you not care about stable.

**Comment by tangyoha** [comment]
https://github.com/tangyoha/telegram_media_downloader

**Comment by DamianMorozov** [comment]
I have the same problem. Few files have zero size.
It's not network error. it's the program download method error.

**Comment by DamianMorozov** [comment]
How can I redowload zero size files?

**Comment by tangyoha** [comment]
try this https://github.com/tangyoha/telegram_media_downloader

**Comment by Richman881** [comment]
> 

i'll try,,,ths

**Comment by Richman881** [comment]
![1](https://user-images.githubusercontent.com/118971188/203983815-b74ca618-e285-4b4c-9b1e-58288779d304.png)
![2](https://user-images.githubusercontent.com/118971188/203983822-084f7e7a-26e8-47bf-a92a-0d7aa80f2429.png)
![3](https://user-images.githubusercontent.com/118971188/203983835-fd5d03cc-65d8-4884-873c-2ef7051f21c4.png)

**Comment by Richman881** [comment]
> try this https://github.com/tangyoha/telegram_media_downloader

 The logic of this version is much better，

It will automatically compare the downloaded files and automatically select whether to redownload it.

`           INFO     Start creating a new auth key on DC4             auth.py:82
           INFO     Using proxy 127.0.0.1                             tcp.py:72
           INFO     Connecting...                              connection.py:56
           Level 777 F:\te_download\telegram_media_down media_downloader.py:242
                     loader-2.0.2\BIOS ARCHIVE                                 
                     💻💻\2018_01\3489 - Dell Optiplex                         
                     755  25X32VSIG-A01.bin.rar alreay                         
                     download,download skipped. `

**Comment by DamianMorozov** [comment]
> > try this https://github.com/tangyoha/telegram_media_downloader
> 
> The logic of this version is much better，
> 
> It check if the file download then skipped, else redownload it.

It is not working too!
I have tried your repo.
Step 1. Open any file in text editor, delete all data into the file.
Step 2. Change  back the option "last_read_message_id: 0".
Step 3. Start "python media_downloader.py".
Step 4. Set that message "<file> alreay download,download skipped.".

**Comment by Dineshkarthik** [comment]
> > > try this https://github.com/tangyoha/telegram_media_downloader
> 
> > The logic of this version is much better，
> 
> > It check if the file download then skipped, else redownload it.
> 
> 
> 
> The same error. Try to do that steps:
> 
> Step 1. Open any file in text editor, delete all data into the file.
> 
> Step 2. Change  back the option "last_read_message_id: 0".
> 
> Step 3. Start "python media_downloader.py".
> 
> Step 4. Set that message "file alreay download,download skipped.".

In step 1 you need to delete the downloaded file itself not just the data of the file.

**Comment by DamianMorozov** [comment]
I describe the simulate of situation.
The original problem is the same - the some files have 0 size of bytes.
And i think, the program must to redownload that files in auto mode.

**Comment by tsinit2001** [comment]
> My network is not very stable because I use a VPN, so when I download, some random files appear with 0bit, but the file is not 0bit in telegram.i'll push some pics bout that later
I also encountered the same situation. Downloaded file, 0 bytes. I'm sure it's not a problem with the VPN. Since I use several VPSs deployed around the world, this happens randomly.
Currently, I am using the one recommended by the boss below:
https://github.com/tangyoha/telegram_media_downloader
this version. It cannot avoid the error of downloading 0-byte files, but you can manually delete the 0-byte file, modify the config and restart the download, download repeatedly, and finally get the complete channel and group media files.
Don't worry, when downloading repeatedly, it will skip the files that have been downloaded and have not been deleted, so there will be no waste of traffic.

**Comment by DamianMorozov** [comment]
Try the [TgDownloader](https://github.com/DamianMorozov/TgDownloader) to solve that problem.
