### ISSUE TITLE
Is it possible to specify another save folder?

### ISSUE THREAD

**Issue by tsinit2001** [Dineshkarthik/telegram_media_downloader#378]
My disk space is relatively small, so I hope to support saving the downloaded content to other path. Or simply save to rclone to the local OneDrive network disk

**Comment by art435** [comment]
Yes. this feature is needed.

**Comment by DamianMorozov** [comment]
Try the [TgDownloader](https://github.com/DamianMorozov/TgDownloader) to solve that problem.

**Comment by tsinit2001** [comment]
Thank you!
