### ISSUE TITLE
GetChatHistory.get_chat_history() got an unexpected keyword argument 'reverse'

### ISSUE THREAD

**Issue by raelestate** [Dineshkarthik/telegram_media_downloader#379]
DeprecationWarning: There is no current event loop
  main_loop = asyncio.get_event_loop()

**Comment by tangyoha** [comment]
@rhyll123123 hi, you should run:
```
pip3 uninstall pyrogram
pip3 install -r requirements.txt
```

**Comment by ssjdm** [comment]
> 
Traceback (most recent call last):
  File "C:\tg\telegram_media_downloader\media_downloader.py", line 7, in <module>
    import pyrogram
ModuleNotFoundError: No module named 'pyrogram'

**Comment by tangyoha** [comment]
> > 
> 
> Traceback (most recent call last):
> 
>   File "C:\tg\telegram_media_downloader\media_downloader.py", line 7, in <module>
> 
>     import pyrogram
> 
> ModuleNotFoundError: No module named 'pyrogram'

pip3 install -r requirements.txt

**Comment by tymon42** [comment]
@raelestate The [pyrogram](https://github.com/Dineshkarthik/pyrogram) is not used in the project Author import a private [pyrogram](https://github.com/Dineshkarthik/pyrogram) instead. You should learn that from the first line in the requirements.txt .  

And I recommend you @ssjdm run this project in a new `venv` and run `pip3 install -r requirements.txt` if you can't uninstall your pyrogram.

**Comment by Dineshkarthik** [comment]
Please use the custom pyrogram fork
```sh
pip uninstall pyrogram
pip install https://github.com/Dineshkarthik/pyrogram/archive/refs/heads/master.zip
```
