### ISSUE TITLE
setup err

### ISSUE THREAD

**Issue by chinajuan2** [Dineshkarthik/telegram_media_downloader#382]
**Python Version**
Python: [e.g. 3.11.1]

**OS:**
win10

**Additional context**

Installing collected packages: pyaes, commonmark, TgCrypto, PyYAML, pysocks, pygments, rich, Pyrogram
  DEPRECATION: pyaes is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyaes ... done
  DEPRECATION: Pyrogram is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for Pyrogram ... done
Successfully installed PyYAML-6.0 Pyrogram-2.0.69 TgCrypto-1.2.3 commonmark-0.9.1 pyaes-1.6.1 pygments-2.13.0 pysocks-1.7.1 rich-12.5.1

**Comment by Dineshkarthik** [comment]
This is a deprecation warning not an error
