### ISSUE TITLE
pyrogram.errors.exceptions.flood_420.FloodWait: T

### ISSUE THREAD

**Issue by luckyRRR** [Dineshkarthik/telegram_media_downloader#383]
pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 60259 seconds is required (caused by "auth.SendCode")

**Comment by caozhg** [comment]
wait of 60259 seconds

**Comment by caozhg** [comment]
> pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 60259 seconds is required (caused by "auth.SendCode")
wait of 60259 seconds
