### ISSUE TITLE
Automaticaly retry the failed ID's

### ISSUE THREAD

**Issue by art435** [Dineshkarthik/telegram_media_downloader#387]
**Is your feature request related to a problem? Please describe.**
Now the failed ID's are never retried, we have to manually run the script a few times.

**Describe the solution you'd like**
The script should do this automatically.

**Describe alternatives you've considered**
Maybe this should be an option that users can enable or disable from config file.

**Comment by DamianMorozov** [comment]
Try the [TgDownloader](https://github.com/DamianMorozov/TgDownloader) to solve that problem.

**Comment by art435** [comment]
Thanks! Already did, I left you a message.
