### ISSUE TITLE
How to download files from a specific date period?

### ISSUE THREAD

**Issue by diertian** [Dineshkarthik/telegram_media_downloader#396]
For example, I want to download all audio files from 2022-12-01 to 2022-12-31, including mp3, m4a, ape, flac, wav, etc.

**Comment by alikaraali** [comment]
That is a good question indeed! Do you have any suggestion @Dineshkarthik ?

**Comment by tangyoha** [comment]
### Download files from a specific date period
* [en](https://github.com/tangyoha/telegram_media_downloader/wiki/How-to-use-Filter)
* [中文](https://github.com/tangyoha/telegram_media_downloader/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%BF%87%E6%BB%A4%E5%99%A8)

chat_id: your_chat_id
download_filter:
   'your_chat_id': message_date >= 2022-12-01 and message_date <= 2022-12-31
