### ISSUE TITLE
Only to download a part I want.

### ISSUE THREAD

**Issue by jianala** [Dineshkarthik/telegram_media_downloader#430]
A channel have many videos ，I want to get some of it but not all of it. Time  would wasted if downloading all videos.It is hoped that you can add the entry to select download video, match regular, fuzzy download and so on.

**Comment by tangyoha** [comment]
### Download files from a specific date period
* [en](https://github.com/tangyoha/telegram_media_downloader/wiki/How-to-use-Filter)
* [中文](https://github.com/tangyoha/telegram_media_downloader/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%BF%87%E6%BB%A4%E5%99%A8)

message_date >= 2022-12-01 and message_date <= 2022-12-31

**Comment by jianala** [comment]
Thank you very much.
