### ISSUE TITLE
parallel downloads

### ISSUE THREAD

**Issue by ezpuzz** [Dineshkarthik/telegram_media_downloader#5]
Hi @Dineshkarthik , thanks so much for this script!  I find it very useful for downloading mp3s from telegram chats.

I was wondering if it would be possible to download multiple files in parallel to make the downloading faster?

**Comment by fabianski7** [comment]
up

**Comment by Dineshkarthik** [comment]
Before implementing parallel downloads:
```
real	   2m51.00s  <----
user	    0m7.16s
sys	    0m5.02s
```

After implementing parallel downloads:
```
real	    0m55.582s  <----
user	    0m11.59s
sys	    0m5.84s
```
