### ISSUE TITLE
Exception `File reference expired` causing script stoped

### ISSUE THREAD

**Issue by Lqlsoftware** [Dineshkarthik/telegram_media_downloader#52]
I am using a try/except in the script and after the all-night downloading, it must occur some exception which I didn't print (my bad) and it saved the config and exited.
FYI, the exception stacks in Pyrogram:
```
INFO:__main__:Media downloaded - None
ERROR:pyrogram.client:[400 Bad Request]: [400 FILE_REFERENCE_EXPIRED] (caused by "upload.GetFile")
Traceback (most recent call last):
  File "/home/robinlu/.local/lib/python3.8/site-packages/pyrogram/client.py", line 928, in get_file
    r = await session.send(
  File "/home/robinlu/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "/home/robinlu/.local/lib/python3.8/site-packages/pyrogram/session/session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "/home/robinlu/.local/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 68, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BadRequest: [400 Bad Request]: [400 FILE_REFERENCE_EXPIRED] (caused by "upload.GetFile")
```
What's shocked me is that when I restart the script, it works fine at the expired reference.

**Comment by Lqlsoftware** [comment]
Seems related to #43. My guess is some file references expired when waiting for other downloading.

**Comment by Dineshkarthik** [comment]
I think this is what that is causing the issue - https://core.telegram.org/api/file_reference
We should catch this `FILE_REFERENCE_EXPIRED` exception and re-fetch the message to get the `updated file_reference` and use it to download the file.

**Comment by Lqlsoftware** [comment]
Ok, I will see what I can do.
