### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by creazytom** [Dineshkarthik/telegram_media_downloader#55]
My api_id is correct, running telegram_media_downloader reports an error
  python3 media_downloader.py
Traceback (most recent call last):
   File "media_downloader.py", line 290, in <module>
     begin_import(config, pagination_limit=100)
   File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
     return future.result()
   File "media_downloader.py", line 243, in begin_import
     api_id=config["x3971xx"],
KeyError:'x3971xx'

**Comment by Dineshkarthik** [comment]
Hi,

You have to add your configurations to `config.yaml` not in `media_downloader.py` as a key for a dictionary.
Add your api_id [here](https://github.com/Dineshkarthik/telegram_media_downloader/blob/master/config.yaml#L2)

**Comment by creazytom** [comment]
> 你好
> 
> 您必须添加配置，`config.yaml`而不要将其添加`media_downloader.py`为字典的键。[在此处](https://github.com/Dineshkarthik/telegram_media_downloader/blob/master/config.yaml#L2)
> 添加您的api_id[](https://github.com/Dineshkarthik/telegram_media_downloader/blob/master/config.yaml#L2)

thanks
