### ISSUE TITLE
下着下着停止了

### ISSUE THREAD

**Issue by creazytom** [Dineshkarthik/telegram_media_downloader#60]
我好像没看到有上传的选项，这个是需要关闭上传吗
INFO:pyrogram.syncer:Synced "media_downloader" in 17052.4 ms
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:[1] Retrying "upload.GetFile" due to
INFO:pyrogram.session.session:[1] Retrying "upload.GetFile" due to
已杀死

**Comment by Dineshkarthik** [comment]
@creazytom please follow the available Bug Report template and edit the above.

**Comment by Lqlsoftware** [comment]
Seems your VPN is not stable for multi-task downloading.

**Comment by Dineshkarthik** [comment]
There is no actual upload and the script doesn't support uploading media to telegram.
[upload.GetFile](https://core.telegram.org/method/upload.getFile) is the method used to download the files.

**Comment by Dineshkarthik** [comment]
Please re-open the issue if the above doesn't answer what you asked.
