### ISSUE TITLE
how to download group files?

### ISSUE THREAD

**Issue by weigeloveu** [Dineshkarthik/telegram_media_downloader#7]
like this "https://web.telegram.org/#/im?p=s1277084497_17461191378986610971"
i tried 1277084497 as chat id,but got an error
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: [400 PEER_ID_INVALID]: The id/access_hash combination is invalid

**Comment by Dineshkarthik** [comment]
@weigeloveu  based on the error message can you verify once again whether you have entered the `api_id` and `api_hash` in `config.yaml` correctly?

**Comment by loeveo** [comment]
不公开群不能用id.只能用邀请链接里那串

**Comment by loeveo** [comment]
好吧，只是因为有一个同邀请名的群.实际上，目前这个程序无法下载，未公开的群
