### ISSUE TITLE
my_api_id error

### ISSUE THREAD

**Issue by abdulkerimbozdag** [Dineshkarthik/telegram_media_downloader#72]
Hi, when I run the command I get an error like this:

$ python3 media_downloader.py
Telegram Media Downloader v0.3.0, Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
Licensed under the terms of the MIT License

INFO:media_downloader:Device: CPython 3.8.6 - Telegram Media Downloader 0.3.0
INFO:media_downloader:System: Windows 10 (EN)
Traceback (most recent call last):
  File "media_downloader.py", line 364, in <module>
    main()
  File "media_downloader.py", line 345, in main
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "media_downloader.py", line 297, in begin_import
    api_id=config["my_api_id"],
KeyError: 'my_api_id'

**Comment by Dineshkarthik** [comment]
@abdulkerimbozdag this is the actual code [media_downloader.py#L297](https://github.com/Dineshkarthik/telegram_media_downloader/blob/master/media_downloader.py#L297) 

```py
api_id=config["api_id"],
```
>You changed it that is why it is failing.

Configure your `api_id` and `api_hash` in [config.yaml](https://github.com/Dineshkarthik/telegram_media_downloader/blob/master/config.yaml). To know how to get your api_id & api_hash check [configuration](https://github.com/Dineshkarthik/telegram_media_downloader#configuration) section of the README file.

**Comment by abdulkerimbozdag** [comment]
Thanks a lot. I want to make a request. For example, the name of the downloads folder could be "telegram_chat_id". Downloaded files can also be found in the folder of their genre, depending on their type.. C:\Users\my_pc\Desktop\telegram_media_downloader\"chat_id"\photo or C:\Users\my_pc\Desktop\telegram_media_downloader\"chat_id"\document

**Comment by Dineshkarthik** [comment]
Sure, will add it to the backlog of feature requests.

If you come across any other issues open a new Bug Report.
