### ISSUE TITLE
Enter phone number or bot token: INFO:pyrogram.session.session:PingTask started

### ISSUE THREAD

**Issue by 5536086** [Dineshkarthik/telegram_media_downloader#84]
Excuse me, what does this phone number mean? Where should I get it?

**Comment by 5536086** [comment]
pyrogram.errors.exceptions.unauthorized_401.UserDeactivatedBan: [401 USER_DEACTIVATED_BAN]: The user has been deleted/deactivated (caused by "updates.GetState")

**Comment by peepopoggers** [comment]
I have this issue too. Why would this happen? The only thing i can think of is the URL i was meant to put for the app, but i just put telegram.org as the url because i did not know what to put. any help would be appreciated

**Comment by Dineshkarthik** [comment]
@peepopoggers I don't get you. What error are you getting exactly?
And where did you enter the url?

**Comment by tantao700** [comment]
i have the same issue and resolved by input your phone register in TG.
Actually, this is not issue, the telegram server found this device you run is new device, and check the risk.
