### ISSUE TITLE
This script deleted my account,

### ISSUE THREAD

**Issue by 5536086** [Dineshkarthik/telegram_media_downloader#85]
This script deleted my account, pyrogram.errors.exceptions.unauthorized_401.UserDeactivatedBan: [401 USER_DEACTIVATED_BAN]: The user has been deleted/deactivated (caused by "updates.GetState")

**Comment by Dineshkarthik** [comment]
Telegram media downloader doesn't have any code/functionality that deals with any type of user account editing or updation.

Once you recreated your user you can retry with the script and you can download.

**Comment by 5536086** [comment]
I applied to the TG official to unblock my account, but all my information was lost. I tried the script again. No accident, my account was blocked again! I suspect that there is an operation that triggers the banning of the account in the script, please check, now my account has been banned twice in the same way!

**Comment by Dineshkarthik** [comment]
I can assure you that the script does nothing of that sort, can you make sure that the channel you are trying to access is not some copyright-infringing channel? make sure you are entering the correct password If you had a password enabled
also clear any state files `media_downloader.session` or any files ending with `.session`.

**Comment by Dineshkarthik** [comment]
> I applied to the TG official to unblock my account, but all my information was lost. I tried the script again. No accident, my account was blocked again! I suspect that there is an operation that triggers the banning of the account in the script, please check, now my account has been banned twice in the same way!

can you share the entire log? It will help me identify the problem. It will be better if you can use the issue template and share other required details.

**Comment by 5536086** [comment]
When I tried to start the script for the second time, my account was already empty. I manually added a TG channel and then executed the script to download. The result was still blocked. Therefore, there is no possibility that the illegal content will cause the account to be blocked. Sex, I’m just a little worried that maybe some code in the script will trigger the TG system protection mechanism

**Comment by 5536086** [comment]
> e and share other required details.

Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.

**Comment by Dineshkarthik** [comment]
> > e and share other required details.
> 
> Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.

share the channel you are trying to download.

**Comment by Dineshkarthik** [comment]
Please share your config file except for the api_hash and api_id

**Comment by 5536086** [comment]
> e and share other required details.

Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.

> > > e and share other required details.
> > 
> > 
> > Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.
> 
> share the channel you are trying to download.

https://t.me/scjchannel

**Comment by 5536086** [comment]
this

> Please share your config file except for the api_hash and api_id

this
![QQ20210331150012](https://user-images.githubusercontent.com/20472307/113103484-e819f480-9231-11eb-997d-d89345f1aee6.png)

**Comment by Dineshkarthik** [comment]
> > > e and share other required details.
> > 
> > 
> > Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.
> 
> share the channel you are trying to download.

![image](https://user-images.githubusercontent.com/7752572/113103531-acfecd80-91ff-11eb-847d-3d63edc9659c.png)

The channel is used to spread pornographic content and is banned/restricted by telegram.

**Comment by 5536086** [comment]
> > > > e and share other required details.
> > > 
> > > 
> > > Now my account has been completely banned, and the official customer service has refused to reply to me, so I don’t have any log records.
> > 
> > 
> > share the channel you are trying to download.
> 
> ![image](https://user-images.githubusercontent.com/7752572/113103531-acfecd80-91ff-11eb-847d-3d63edc9659c.png)
> 
> The channel is used to spread pornographic content and is banned/restricted by telegram.

But this is not enough to cause me to be banned, because I can use the TG export function to export pictures

**Comment by Dineshkarthik** [comment]
I used the channel to run the script and my account is not deleted/deactivated.

```
Telegram Media Downloader v0.3.1, Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
Licensed under the terms of the MIT License

INFO:media_downloader:Device: CPython 3.8.6 - Telegram Media Downloader 0.3.1
INFO:media_downloader:System: Darwin 20.3.0 (EN)
INFO:pyrogram.connection.connection:Connecting...
INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
INFO:pyrogram.session.session:NetworkTask started
INFO:pyrogram.session.internals.msg_id:Time synced: 2021-03-31 07:04:50.192888 UTC
INFO:pyrogram.session.session:NextSaltTask started
INFO:pyrogram.session.session:Next salt in 15m 49s (2021-03-31 09:20:38)
INFO:pyrogram.session.session:Session initialized: Layer 117
INFO:pyrogram.session.session:Device: CPython 3.8.6 - Pyrogram 1.0.7
INFO:pyrogram.session.session:System: Darwin 20.3.0 (EN)
INFO:pyrogram.session.session:Session started
INFO:pyrogram.session.session:PingTask started
INFO:pyrogram.dispatcher:Started 12 HandlerTasks
INFO:pyrogram.syncer:Synced "media_downloader" in 7.75719 ms
INFO:pyrogram.syncer:Synced "media_downloader" in 8.3158 ms
INFO:pyrogram.dispatcher:Stopped 12 HandlerTasks
INFO:pyrogram.session.session:PingTask stopped
INFO:pyrogram.session.session:NextSaltTask stopped
INFO:pyrogram.connection.connection:Disconnected
INFO:pyrogram.session.session:NetworkTask stopped
INFO:pyrogram.session.session:Session stopped
INFO:media_downloader:Updated last read message_id to config file
```

**Comment by Dineshkarthik** [comment]
By any chance are you routing your traffic via a network that telegram might consider as a location that is not related to you and thus flag it as unauthorized access to prevent illegal access of your account?

**Comment by 5536086** [comment]
> 我使用该通道运行脚本，并且未删除/停用我的帐户。
> 
> 配置：
> 
> ```
> api_hash: my-api-hash
> api_id: my-api-id
> chat_id: scjchannel
> file_formats:
>   audio:
>   - all
>   document:
>   - all
>   video:
>   - all
> ids_to_retry: []
> last_read_message_id: 0
> media_types:
> - audio
> - photo
> - video
> - document
> - voice
> ```
> 
> 日志：
> 
> ```
> Telegram Media Downloader v0.3.1, Copyright (C) 2019 Dineshkarthik <https://github.com/Dineshkarthik>
> Licensed under the terms of the MIT License
> 
> INFO:media_downloader:Device: CPython 3.8.6 - Telegram Media Downloader 0.3.1
> INFO:media_downloader:System: Darwin 20.3.0 (EN)
> INFO:pyrogram.connection.connection:Connecting...
> INFO:pyrogram.connection.connection:Connected! Production DC5 - IPv4 - TCPAbridgedO
> INFO:pyrogram.session.session:NetworkTask started
> INFO:pyrogram.session.internals.msg_id:Time synced: 2021-03-31 07:04:50.192888 UTC
> INFO:pyrogram.session.session:NextSaltTask started
> INFO:pyrogram.session.session:Next salt in 15m 49s (2021-03-31 09:20:38)
> INFO:pyrogram.session.session:Session initialized: Layer 117
> INFO:pyrogram.session.session:Device: CPython 3.8.6 - Pyrogram 1.0.7
> INFO:pyrogram.session.session:System: Darwin 20.3.0 (EN)
> INFO:pyrogram.session.session:Session started
> INFO:pyrogram.session.session:PingTask started
> INFO:pyrogram.dispatcher:Started 12 HandlerTasks
> INFO:pyrogram.syncer:Synced "media_downloader" in 7.75719 ms
> INFO:pyrogram.syncer:Synced "media_downloader" in 8.3158 ms
> INFO:pyrogram.dispatcher:Stopped 12 HandlerTasks
> INFO:pyrogram.session.session:PingTask stopped
> INFO:pyrogram.session.session:NextSaltTask stopped
> INFO:pyrogram.connection.connection:Disconnected
> INFO:pyrogram.session.session:NetworkTask stopped
> INFO:pyrogram.session.session:Session stopped
> INFO:media_downloader:Updated last read message_id to config file
> ```

Mine will also appear in these LOG messages, but the number will be blocked after a while

**Comment by 5536086** [comment]
> By any chance are you routing your traffic via a network that telegram might consider as a location that is not related to you and thus flag it as unauthorized access to prevent illegal access of your account?

The problems I encountered made me very confused, hey

**Comment by 5536086** [comment]
I re-register a number and continue to try, do I need a TGbot?

**Comment by Dineshkarthik** [comment]
Which channel are you trying now?

**Comment by 5536086** [comment]
> Which channel are you trying now?

Same channel, hey

**Comment by 5536086** [comment]
I changed a number and a different running environment. It seems that there is no problem for the time being, but what do the screenshots mean? Can't the data be fetched? Waited for a long time, but no data has been downloaded yet.
![QQ20210331150012](https://user-images.githubusercontent.com/20472307/113120855-99298a80-9244-11eb-9f4a-9d8d752a10a6.png)

**Comment by Dineshkarthik** [comment]
I wanted to point out when I try to access the channel you mentioned above I get 0 messages. so I can't download anything from the channel but from your log, I can see there was a photo downloaded when you run it. Not sure why Telegram is not showing any messages to me. Did you try downloading any other channel preferably one which is not restricted for pornography or any other copy-right infringement?

I ran the downloader script to download media from a channel that has a lot of files - `aedahamlibrary_noolakam`, It ran for ` 1h 3m 29s` and processed `6186` messages and downloaded `548` 

files and nothing broke and my account is not banned. I also attached the log file [media_downloader.log](https://github.com/Dineshkarthik/telegram_media_downloader/files/6235458/media_downloader.log) for your reference.

**Comment by 5536086** [comment]
> I wanted to point out when I try to access the channel you mentioned above I get 0 messages. so I can't download anything from the channel but from your log, I can see there was a photo downloaded when you run it. Not sure why Telegram is not showing any messages to me. Did you try downloading any other channel preferably one which is not restricted for pornography or any other copy-right infringement?
> 
> I ran the downloader script to download media from a channel that has a lot of files - `aedahamlibrary_noolakam`, It ran for ` 1h 3m 29s` and processed `6186` messages and downloaded `548` files and nothing broke and my account is not banned. I also attached the log file [media_downloader.log](https://github.com/Dineshkarthik/telegram_media_downloader/files/6235468/media_downloader.log) for your reference.

I mainly download the video, but I can’t grab it. I don’t know if it’s because the video is relatively large

**Comment by Dineshkarthik** [comment]
> I changed a number and a different running environment. It seems that there is no problem for the time being, but what do the screenshots mean? Can't the data be fetched? Waited for a long time, but no data has been downloaded yet.
> ![QQ20210331150012](https://user-images.githubusercontent.com/20472307/113120855-99298a80-9244-11eb-9f4a-9d8d752a10a6.png)

This means there is some message fetches and sync happening with the telegram in the background and also if download files are present the  files are being downloaded in parallel and you will get an info message once the file is completed.

**Comment by Dineshkarthik** [comment]
> > I wanted to point out when I try to access the channel you mentioned above I get 0 messages. so I can't download anything from the channel but from your log, I can see there was a photo downloaded when you run it. Not sure why Telegram is not showing any messages to me. Did you try downloading any other channel preferably one which is not restricted for pornography or any other copy-right infringement?
> > I ran the downloader script to download media from a channel that has a lot of files - `aedahamlibrary_noolakam`, It ran for ` 1h 3m 29s` and processed `6186` messages and downloaded `548` files and nothing broke and my account is not banned. I also attached the log file [media_downloader.log](https://github.com/Dineshkarthik/telegram_media_downloader/files/6235468/media_downloader.log) for your reference.
> 
> I mainly download the video, but I can’t grab it. I don’t know if it’s because the video is relatively large

yeah the sync message you mentioned earlier is also an indication that you are downloading some huge files.
