### ISSUE TITLE
[FEATURE REQUEST] Filters

### ISSUE THREAD

**Issue by fabianski7** [Dineshkarthik/telegram_media_downloader#9]
It would be great to be able to filter by the type of file to be downloaded.
I need to download some files from a group at the university but there are thousands of files of different formats and dates there. If there was an option to filter by file format such as .doc .pdf .epub it would solve a lot of this problem. I believe it will be very useful for other people as well.

If possible a date filter would also be welcome. I think this might be a little harder to do. I currently use this extension for chrome to do this
https://github.com/fattynoparents/Telegram-Media-Downloader
https://chrome.google.com/webstore/detail/telegram-media-downloader/ffhhcekaaamffjnapdckmnkllkmmpfnh?hl=en

**Comment by Dineshkarthik** [comment]
@fabianski7 hi did you try using only `document` as `media_types`.
```
api_hash: your_api_hash
api_id: your_api_id
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- document
```

I hope this is what you are looking for.

**Comment by fabianski7** [comment]
Yes. That's what I'm using.

But my intention was to download only one specific format. Like only `.pdf`

Currently, if you use `document` in `media_type`, all formats will be downloaded

**Comment by Dineshkarthik** [comment]
@fabianski7 now you can download specific file formats. pull in the new changes from master branch and update the config as follows:
```
api_hash: your_api_hash
api_id: your_api_id
chat_id: telegram_chat_id
last_read_message_id: 0
media_types:
- document
file_formats:
  document:
  - pdf
  - epub
```

**Comment by fabianski7** [comment]
after several hours of capturing the messages (I think that's what was happening) I got this error

INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:Send 8 acks
INFO:pyrogram.session.session:Send 8 acks
Traceback (most recent call last):
  File "media_downloader.py", line 202, in <module>
    updated_config = asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "media_downloader.py", line 186, in begin_import
    last_read_message_id = await process_messages(
  File "media_downloader.py", line 165, in process_messages
    message_ids = await asyncio.gather(
  File "media_downloader.py", line 119, in download_media
    file_ref, file_name, file_format = await _get_media_meta(
  File "media_downloader.py", line 67, in _get_media_meta
    file_name = os.path.join(THIS_DIR, _type, media_obj.file_name)
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

No files have been downloaded.

Well, it's a pretty big group with a lot of files, would that be any limitation?

**Comment by fabianski7** [comment]
my config file 
```
api_hash: xxxx
api_id: xxxx
chat_id: xxxx
last_read_message_id: 0
media_types:
- document
file_formats:
  document:
  - mobi
```

**Comment by fabianski7** [comment]
this all generated a `media_downloader.session` file of about 3.2M

**Comment by Dineshkarthik** [comment]
@fabianski7 can you create this as a new issue, we can look into it there.
