### ISSUE TITLE
App do not do make install

### ISSUE THREAD

**Issue by sadupl** [Dineshkarthik/telegram_media_downloader#92]
**Describe the bug**
I follow instructions and "make install" give me an error.

`make install`
`pip install --upgrade pip setuptools `
`make: pip: Command not found`
`make: *** [Makefile:6: install] Error 127`
`
Screenshot:
![screen](https://user-images.githubusercontent.com/55146890/115495835-c88e4e80-a268-11eb-94eb-708ca1fb752a.png)

**Python Version**
Python: 3.8.5

**OS:**
Ubuntu 20.04

**Comment by Dineshkarthik** [comment]
@sadupl replace all `pip` to `pip3` in your make file and run `make install` it will work.

**Comment by Dineshkarthik** [comment]
Pull the latest changes and it should work now.
