### ISSUE TITLE
下载名称一样的文件，新文件会覆盖旧文件

### ISSUE THREAD

**Issue by Discover623** [Dineshkarthik/telegram_media_downloader#97]
![2021-05-10-11](https://user-images.githubusercontent.com/38528853/117666238-3b3e7a00-b1d6-11eb-8f32-fd6bdabded4a.png)
怎样重命名，保留所有文件

**Comment by bajins** [comment]
> ![2021-05-10-11](https://user-images.githubusercontent.com/38528853/117666238-3b3e7a00-b1d6-11eb-8f32-fd6bdabded4a.png)
> 怎样重命名，保留所有文件

https://github.com/bajins/telegram_media_downloader 已经提交pr，不知道他会不会同意合并

**Comment by Dineshkarthik** [comment]
> > ![2021-05-10-11](https://user-images.githubusercontent.com/38528853/117666238-3b3e7a00-b1d6-11eb-8f32-fd6bdabded4a.png)
> > How to rename and keep all files
> 
> https://github.com/bajins/telegram_media_downloader has submitted pr, I don’t know if he will agree to the merger

what you are trying to do is already available as mentioned in the PR
